import 'package:kf_openapi_generated/api.dart';

Patient demoPatient = Patient(
  firstName: "Dhritiman",
  lastName: "Banerjee",
  fullName: "Dhritiman Banerjee",
  age: 52,
  gender: PatientGenderEnum.male,
  mobileNumber: "+91 9876543210",
  aadharNumber: "1234 1234 1234 1234",
  dateOfBirth: DateTime.now(),
  id: "e7f5d828-2028-4034-8f3d-19b62ac3d0eb",
  localityName: "Anand Vatika",
  medicalVisits: visits,
);

var visits = [
  PatientVisit(
    visitDate: DateTime.now(),
    medicalCenter: HealthCenter(name: "Anand Vatika Healtcare Center"),
    caseSeverity: PatientVisitCaseSeverityEnum.green,
    doctor: Doctor(name: "Anand Kumar"),
    repeatVisit: true,
    symptom1: SymptomsEnum(symptomName: "Headache"),
    symptom2: SymptomsEnum(symptomName: "Stomach Ache"),
    symptom3: SymptomsEnum(symptomName: "Runny nose"),
    otherSymptoms: "Red eyes",
    height: "5'10\"",
    weight: "60 Kg",
    temperature: "98.8 C",
    bloodPressure: "120/80",
    pulseRate: "72 bpm",
    oxygenLevel: "100 spo2",
    vitalStatisticsOther: "lung vol 2L",
    diagnosis: "Flu",
    medicine1: MedicineEnum(medicineName: "Paracetamol"),
    med1Qty: 5,
    medicine2: MedicineEnum(medicineName: "Calpol"),
    med2Qty: 5,
    medicine3: MedicineEnum(medicineName: "Benadryl"),
    med3Qty: 5,
    medicine4: MedicineEnum(medicineName: "Honeytus"),
    med4Qty: 5,
    medicineInstructions: "One daily after dinner",
    dietaryInstructions: "Daliya",
    differentialDiagnosis: "Flu",
    differentialRecommendation: "Drink lots of boiled water",
  ),
  PatientVisit(
    visitDate: DateTime.now(),
    medicalCenter: HealthCenter(name: "Anand Vatika Healtcare Center"),
    caseSeverity: PatientVisitCaseSeverityEnum.orange,
    doctor: Doctor(name: "Anand Kumar"),
    repeatVisit: true,
    symptom1: SymptomsEnum(symptomName: "Headache"),
    medicineInstructions: "One daily after dinner",
    dietaryInstructions: "Daliya",
    differentialDiagnosis: "Flu",
    differentialRecommendation: "Drink lots of boiled water",
  ),
  PatientVisit(
    visitDate: DateTime.now(),
    medicalCenter: HealthCenter(name: "Anand Vatika Healtcare Center"),
    caseSeverity: PatientVisitCaseSeverityEnum.red,
    doctor: Doctor(name: "Anand Kumar"),
    repeatVisit: true,
    symptom1: SymptomsEnum(symptomName: "Headache"),
    medicineInstructions: "One daily after dinner",
    dietaryInstructions: "Daliya",
    differentialDiagnosis: "Flu",
    differentialRecommendation: "Drink lots of boiled water",
  ),
];
