const es = {
  common: {
    or: 'o',
    cancel: 'Cancelar',
    reset: 'Reiniciar',
    save: 'Guardar',
    search: 'Buscar',
    edit: 'Editar',
    remove: 'Eliminar',
    new: 'Nuevo',
    export: 'Exportar a Excel',
    noDataToExport: 'No hay datos para exportar',
    import: 'Importar',
    discard: 'Descartar',
    yes: 'Si',
    no: 'No',
    pause: 'Pausa',
    areYouSure: '¿Estás seguro?',
    view: 'Ver',
    destroy: 'Eliminar',
    mustSelectARow: 'Debe seleccionar una fila',
    start: 'Comienzo',
    end: 'Final',
    select: 'Seleccione',
    continue: 'Continúa',
    filters: 'Filtros',
  },
  app: {
    title: 'Aplicación',
  },
  api: {
    menu: 'API',
  },
  entities: {
    patient: {
        name: 'patient',
        label: 'Patients',
        menu: 'Patients',
        exporterFileName: 'exportacion_patient',
        list: {
          menu: 'Patients',
          title: 'Patients',
        },
        create: {
          success: 'Patient guardado con éxito',
        },
        update: {
          success: 'Patient guardado con éxito',
        },
        destroy: {
          success: 'Patient eliminado con éxito',
        },
        destroyAll: {
          success: 'Patient(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Patient',
        },
        fields: {
          id: 'Id',
          'medicalCenter': 'MedicalCenter',
          'registrationNumber': 'Registration Number',
          'firstName': 'FirstName',
          'middleName': 'MiddleName',
          'lastName': 'LastName',
          'fullName': 'Full Name',
          'gender': 'Gender',
          'ageRange': 'Age',
          'age': 'Age',
          'localityName': 'Locality Name',
          'mobileNumber': 'Mobile Phone Number',
          'aadharNumber': 'Aadhar Card Number',
          'dateOfBirthRange': 'Date Of Birth',
          'dateOfBirth': 'Date Of Birth',
          'picture': 'Picture',
          'medicalHistory': 'MedicalHistory',
          'medicalVisits': 'Medical Visits',
          'medicalDocuments': 'Medical Documents',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {
          'gender': {
            'Male': 'Male',
            'Female': 'Female',
          },
        },
        placeholders: {
          'registrationNumber': 'Auto-generated',
        },
        hints: {
          'medicalCenter': 'Medical center for patient',
          'fullName': 'Autogenerated by the system',
        },
        new: {
          title: 'Nuevo Patient',
        },
        view: {
          title: 'Ver Patient',
        },
        importer: {
          title: 'Importar Patients',
          fileName: 'patient_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    healthCenter: {
        name: 'healthCenter',
        label: 'HealthCenters',
        menu: 'HealthCenters',
        exporterFileName: 'exportacion_healthCenter',
        list: {
          menu: 'HealthCenters',
          title: 'HealthCenters',
        },
        create: {
          success: 'Health Center guardado con éxito',
        },
        update: {
          success: 'Health Center guardado con éxito',
        },
        destroy: {
          success: 'Health Center eliminado con éxito',
        },
        destroyAll: {
          success: 'Health Center(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Health Center',
        },
        fields: {
          id: 'Id',
          'name': 'Name',
          'address': 'Address',
          'phoneNumber': 'Phone Number',
          'warehouseLicenceNumber': 'WarehouseLicenceNumber',
          'isHeadoffice': 'Is Headoffice',
          'adminName': 'Admin Name',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Health Center',
        },
        view: {
          title: 'Ver Health Center',
        },
        importer: {
          title: 'Importar HealthCenters',
          fileName: 'healthCenter_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    patientVisit: {
        name: 'patientVisit',
        label: 'PatientVisits',
        menu: 'PatientVisits',
        exporterFileName: 'exportacion_patientVisit',
        list: {
          menu: 'PatientVisits',
          title: 'PatientVisits',
        },
        create: {
          success: 'PatientVisit guardado con éxito',
        },
        update: {
          success: 'PatientVisit guardado con éxito',
        },
        destroy: {
          success: 'PatientVisit eliminado con éxito',
        },
        destroyAll: {
          success: 'PatientVisit(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar PatientVisit',
        },
        fields: {
          id: 'Id',
          'patient': 'Patient',
          'medicalCenter': 'Medical Center',
          'department': 'Department',
          'doctor': 'Doctor',
          'visitDateRange': 'Visit Date',
          'visitDate': 'Visit Date',
          'repeatVisit': 'Repeat Visit',
          'symptom1': 'Symptom1',
          'symptom2': 'Symptom2',
          'symptom3': 'Symptom3',
          'otherSymptoms': 'Other Symptoms',
          'height': 'Height',
          'weight': 'Weight',
          'temperature': 'Temperature',
          'bloodPressure': 'Blood Pressure',
          'pulseRate': 'Pulse Rate',
          'oxygenLevel': 'Blood Oxygen Level',
          'vitalStatisticsOther': 'Other vital statistics',
          'diagnosis': 'Clinical Diagnosis',
          'caseSeverity': 'Case Severity',
          'medicine1': 'Medicine #1',
          'med1QtyRange': 'Medicine1 Quantity',
          'med1Qty': 'Medicine1 Quantity',
          'med1Supplied': 'Medicine #1 Supplied?',
          'medicine2': 'Medicine #2',
          'med2QtyRange': 'Medicine2 Quantity',
          'med2Qty': 'Medicine2 Quantity',
          'med2Supplied': 'Medicine 2 Supplied',
          'medicine3': 'Medicine #3',
          'med3QtyRange': 'Medicine3 Quantity',
          'med3Qty': 'Medicine3 Quantity',
          'med3Supplied': 'Medicine #3 Supplied',
          'medicine4': 'Medicine #4',
          'med4QtyRange': 'Medicine4 Quantity',
          'med4Qty': 'Medicine4 Quantity',
          'med4Supplied': 'Medicine #4 Supplied',
          'medicineInstructions': 'Medicine Instructions',
          'requestedLabs': 'Lab Diagnostics',
          'dietaryInstructions': 'DietaryInstructions',
          'isTelemedReferral': 'Telemedicine Referral',
          'medicineCopayRange': 'Medicine Copay (Rs)',
          'medicineCopay': 'Medicine Copay (Rs)',
          'doctorCopayRange': 'Doctor Copay (Rs)',
          'doctorCopay': 'Doctor Copay (Rs)',
          'telemedCopayRange': 'Telemed Copay (Rs)',
          'telemedCopay': 'Telemed Copay (Rs)',
          'referralHospital': 'Referral Hospital',
          'referredSpecialistDoctor': 'Referred to Specialist Doctor',
          'returnIn': 'Return In',
          'telemedicineDoctor': 'Telemedicine Doctor',
          'telemedicineConsultDateRange': 'Telemed Consult Date',
          'telemedicineConsultDate': 'Telemed Consult Date',
          'differentialDiagnosis': 'Telemedicine Diagnosis',
          'differentialRecommendation': 'Telemedicine Doctor Recommendation',
          'finalNotes': 'Final Notes',
          'prescriptionFills': 'PrescriptionFills',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {
          'department': {
            'General': 'General',
            'Eyecare': 'Eyecare',
            'Homeo': 'Homeo',
            'Dentist': 'Dentist',
          },
          'caseSeverity': {
            'Green': 'Green',
            'Orange': 'Orange',
            'Red': 'Red',
          },
          'returnIn': {
            '1week': '1week',
            '2weeks': '2weeks',
            '3weeks': '3weeks',
            '4weeks': '4weeks',
            '6weeks': '6weeks',
            '2months': '2months',
            '3months': '3months',
            '4months': '4months',
            '6months': '6months',
            '1year': '1year',
          },
        },
        placeholders: {
          'caseSeverity': 'Green',
        },
        hints: {
          'repeatVisit': 'Has patient come before in past 2 weeks for the same symptoms',
          'height': 'Height (5\'6 or 145cm)',
          'weight': 'Weight (65 kg)',
          'temperature': 'Patient temperature (98.6)',
          'bloodPressure': 'Blood pressure (120/80)',
          'pulseRate': 'Pulse rate (60)',
          'oxygenLevel': 'Blood oxygen level (100)',
          'caseSeverity': 'How severe is this case (red, green, orange)',
          'med1Supplied': 'Was this supplied from stock?',
          'med2Supplied': 'Was this supplied from stock?',
          'med3Supplied': 'Was this medicine provided from stock dispensary',
          'med4Supplied': 'Was this medicine supplied from local stock?',
          'referredSpecialistDoctor': 'Name of specialist doctor patient is being referred to',
          'telemedicineConsultDate': 'Date of review by the telemedicine professional',
          'differentialDiagnosis': 'Differential diagnosis by the telemedicine doctor',
          'differentialRecommendation': 'Recommended next steps by the telemedicine doctor',
          'finalNotes': 'Final notes from the rural healthcare professional',
        },
        new: {
          title: 'Nuevo PatientVisit',
        },
        view: {
          title: 'Ver PatientVisit',
        },
        importer: {
          title: 'Importar PatientVisits',
          fileName: 'patientVisit_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    medicineEnum: {
        name: 'medicineEnum',
        label: 'Medicines',
        menu: 'Medicines',
        exporterFileName: 'exportacion_medicineEnum',
        list: {
          menu: 'Medicines',
          title: 'Medicines',
        },
        create: {
          success: 'Medicine guardado con éxito',
        },
        update: {
          success: 'Medicine guardado con éxito',
        },
        destroy: {
          success: 'Medicine eliminado con éxito',
        },
        destroyAll: {
          success: 'Medicine(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Medicine',
        },
        fields: {
          id: 'Id',
          'medicineName': 'Medicine Name',
          'keptInStock': 'Kept In Stock',
          'isCommon': 'Commonly Prescribed',
          'medicineCategory': 'MedicineCategory',
          'genericName': 'Generic Name',
          'compositionName': 'Composition Name',
          'msrpRange': 'MSRP',
          'msrp': 'MSRP',
          'centralGSTRange': 'CentralGST',
          'centralGST': 'CentralGST',
          'stateGSTRange': 'State GST',
          'stateGST': 'State GST',
          'unit': 'Unit',
          'tabletsPerStripRange': 'Tablets Per Strip',
          'tabletsPerStrip': 'Tablets Per Strip',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {
          'unit': {
            'STRIP': 'STRIP',
            'BOTTLE': 'BOTTLE',
            'DROP': 'DROP',
            'TUBE': 'TUBE',
          },
        },
        placeholders: {
          'genericName': 'Acetaminophen',
        },
        hints: {
          'genericName': 'Drug composition name',
        },
        new: {
          title: 'Nuevo Medicine',
        },
        view: {
          title: 'Ver Medicine',
        },
        importer: {
          title: 'Importar Medicines',
          fileName: 'medicineEnum_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    diagnosticEnum: {
        name: 'diagnosticEnum',
        label: 'Diagnostic Labs',
        menu: 'Diagnostic Labs',
        exporterFileName: 'exportacion_diagnosticEnum',
        list: {
          menu: 'Diagnostic Labs',
          title: 'Diagnostic Labs',
        },
        create: {
          success: 'Diagnostic Lab guardado con éxito',
        },
        update: {
          success: 'Diagnostic Lab guardado con éxito',
        },
        destroy: {
          success: 'Diagnostic Lab eliminado con éxito',
        },
        destroyAll: {
          success: 'Diagnostic Lab(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Diagnostic Lab',
        },
        fields: {
          id: 'Id',
          'diagnosticName': 'DiagnosticName',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Diagnostic Lab',
        },
        view: {
          title: 'Ver Diagnostic Lab',
        },
        importer: {
          title: 'Importar Diagnostic Labs',
          fileName: 'diagnosticEnum_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    doctor: {
        name: 'doctor',
        label: 'Doctors',
        menu: 'Doctors',
        exporterFileName: 'exportacion_doctor',
        list: {
          menu: 'Doctors',
          title: 'Doctors',
        },
        create: {
          success: 'Doctor guardado con éxito',
        },
        update: {
          success: 'Doctor guardado con éxito',
        },
        destroy: {
          success: 'Doctor eliminado con éxito',
        },
        destroyAll: {
          success: 'Doctor(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Doctor',
        },
        fields: {
          id: 'Id',
          'medicalCenter': 'Medical Center',
          'name': 'Name',
          'specialization': 'Specialization',
          'user': 'User',
          'phone': 'Phone',
          'certifications': 'Certifications',
          'registrationId': 'Registration ID',
          'isRuralHealthcareProfessional': 'Rural Healthcare Professional',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Doctor',
        },
        view: {
          title: 'Ver Doctor',
        },
        importer: {
          title: 'Importar Doctors',
          fileName: 'doctor_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    patientDocument: {
        name: 'patientDocument',
        label: 'Patient Documents',
        menu: 'Patient Documents',
        exporterFileName: 'exportacion_patientDocument',
        list: {
          menu: 'Patient Documents',
          title: 'Patient Documents',
        },
        create: {
          success: 'Patient Document guardado con éxito',
        },
        update: {
          success: 'Patient Document guardado con éxito',
        },
        destroy: {
          success: 'Patient Document eliminado con éxito',
        },
        destroyAll: {
          success: 'Patient Document(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Patient Document',
        },
        fields: {
          id: 'Id',
          'patient': 'Patient',
          'image': 'Image',
          'reportName': 'Report Name',
          'reportDateRange': 'Report Date',
          'reportDate': 'Report Date',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Patient Document',
        },
        view: {
          title: 'Ver Patient Document',
        },
        importer: {
          title: 'Importar Patient Documents',
          fileName: 'patientDocument_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    siteInventory: {
        name: 'siteInventory',
        label: 'Site Inventories',
        menu: 'Site Inventories',
        exporterFileName: 'exportacion_siteInventory',
        list: {
          menu: 'Site Inventories',
          title: 'Site Inventories',
        },
        create: {
          success: 'Site Inventory guardado con éxito',
        },
        update: {
          success: 'Site Inventory guardado con éxito',
        },
        destroy: {
          success: 'Site Inventory eliminado con éxito',
        },
        destroyAll: {
          success: 'Site Inventory(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Site Inventory',
        },
        fields: {
          id: 'Id',
          'siteBatchIdentifier': 'SiteBatchIdentifier',
          'center': 'Center',
          'batchNumber': 'Batch Number',
          'medicine': 'Medicine',
          'inventoryAddDateRange': 'Date Added to Inventory',
          'inventoryAddDate': 'Date Added to Inventory',
          'expiryDateRange': 'Expiry Date',
          'expiryDate': 'Expiry Date',
          'initialCountRange': 'Initial Count',
          'initialCount': 'Initial Count',
          'currentCountRange': 'CurrentCount',
          'currentCount': 'CurrentCount',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {
          'siteBatchIdentifier': 'Autogenerated field used to identify',
        },
        new: {
          title: 'Nuevo Site Inventory',
        },
        view: {
          title: 'Ver Site Inventory',
        },
        importer: {
          title: 'Importar Site Inventories',
          fileName: 'siteInventory_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    symptomsEnum: {
        name: 'symptomsEnum',
        label: 'SymptomsEnums',
        menu: 'SymptomsEnums',
        exporterFileName: 'exportacion_symptomsEnum',
        list: {
          menu: 'SymptomsEnums',
          title: 'SymptomsEnums',
        },
        create: {
          success: 'SymptomsEnum guardado con éxito',
        },
        update: {
          success: 'SymptomsEnum guardado con éxito',
        },
        destroy: {
          success: 'SymptomsEnum eliminado con éxito',
        },
        destroyAll: {
          success: 'SymptomsEnum(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar SymptomsEnum',
        },
        fields: {
          id: 'Id',
          'symptomName': 'SymptomName',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo SymptomsEnum',
        },
        view: {
          title: 'Ver SymptomsEnum',
        },
        importer: {
          title: 'Importar SymptomsEnums',
          fileName: 'symptomsEnum_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    medicalHistory: {
        name: 'medicalHistory',
        label: 'MedicalHistories',
        menu: 'MedicalHistories',
        exporterFileName: 'exportacion_medicalHistory',
        list: {
          menu: 'MedicalHistories',
          title: 'MedicalHistories',
        },
        create: {
          success: 'Medical History guardado con éxito',
        },
        update: {
          success: 'Medical History guardado con éxito',
        },
        destroy: {
          success: 'Medical History eliminado con éxito',
        },
        destroyAll: {
          success: 'Medical History(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Medical History',
        },
        fields: {
          id: 'Id',
          'patient': 'Patient',
          'smoking': 'Smoking',
          'drugUse': 'Drug Use',
          'drink': 'Drink',
          'chronicDisease1': 'ChronicDisease1',
          'chronicDisease2': 'ChronicDisease2',
          'chronicDisease3': 'ChronicDisease3',
          'familyHistory': 'Family History',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {
          'smoking': {
            'None': 'None',
            'Cigarette': 'Cigarette',
            'Bidi': 'Bidi',
            'Ganja': 'Ganja',
            'Multiple': 'Multiple',
            'Other': 'Other',
          },
          'drink': {
            'Occasionally': 'Occasionally',
            'Frequently': 'Frequently',
            'Daily': 'Daily',
          },
        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Medical History',
        },
        view: {
          title: 'Ver Medical History',
        },
        importer: {
          title: 'Importar MedicalHistories',
          fileName: 'medicalHistory_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    chronicDiseaseEnum: {
        name: 'chronicDiseaseEnum',
        label: 'ChronicDiseases',
        menu: 'ChronicDiseases',
        exporterFileName: 'exportacion_chronicDiseaseEnum',
        list: {
          menu: 'ChronicDiseases',
          title: 'ChronicDiseases',
        },
        create: {
          success: 'Chronic Disease guardado con éxito',
        },
        update: {
          success: 'Chronic Disease guardado con éxito',
        },
        destroy: {
          success: 'Chronic Disease eliminado con éxito',
        },
        destroyAll: {
          success: 'Chronic Disease(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Chronic Disease',
        },
        fields: {
          id: 'Id',
          'diseaseName': 'Disease Name',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Chronic Disease',
        },
        view: {
          title: 'Ver Chronic Disease',
        },
        importer: {
          title: 'Importar ChronicDiseases',
          fileName: 'chronicDiseaseEnum_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    medicineCategoryEnum: {
        name: 'medicineCategoryEnum',
        label: 'MedicineCategoryEnums',
        menu: 'MedicineCategoryEnums',
        exporterFileName: 'exportacion_medicineCategoryEnum',
        list: {
          menu: 'MedicineCategoryEnums',
          title: 'MedicineCategoryEnums',
        },
        create: {
          success: 'Medicine Category guardado con éxito',
        },
        update: {
          success: 'Medicine Category guardado con éxito',
        },
        destroy: {
          success: 'Medicine Category eliminado con éxito',
        },
        destroyAll: {
          success: 'Medicine Category(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Medicine Category',
        },
        fields: {
          id: 'Id',
          'categoryName': 'Category Name',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {
          'categoryName': 'Category name',
        },
        hints: {
          'categoryName': 'Respiratory Antibiotic',
        },
        new: {
          title: 'Nuevo Medicine Category',
        },
        view: {
          title: 'Ver Medicine Category',
        },
        importer: {
          title: 'Importar MedicineCategoryEnums',
          fileName: 'medicineCategoryEnum_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    vendor: {
        name: 'vendor',
        label: 'Vendors',
        menu: 'Vendors',
        exporterFileName: 'exportacion_vendor',
        list: {
          menu: 'Vendors',
          title: 'Vendors',
        },
        create: {
          success: 'Vendor guardado con éxito',
        },
        update: {
          success: 'Vendor guardado con éxito',
        },
        destroy: {
          success: 'Vendor eliminado con éxito',
        },
        destroyAll: {
          success: 'Vendor(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Vendor',
        },
        fields: {
          id: 'Id',
          'vendorName': 'Vendor Name',
          'address': 'Address',
          'phone': 'Phone',
          'fax': 'Fax',
          'email': 'Email',
          'tin': 'TIN No.',
          'dlNumber': 'DL No',
          'gstNumber': 'GST Number',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Vendor',
        },
        view: {
          title: 'Ver Vendor',
        },
        importer: {
          title: 'Importar Vendors',
          fileName: 'vendor_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    purchaseOrder: {
        name: 'purchaseOrder',
        label: 'PurchaseOrders',
        menu: 'PurchaseOrders',
        exporterFileName: 'exportacion_purchaseOrder',
        list: {
          menu: 'PurchaseOrders',
          title: 'PurchaseOrders',
        },
        create: {
          success: 'Purchase Order guardado con éxito',
        },
        update: {
          success: 'Purchase Order guardado con éxito',
        },
        destroy: {
          success: 'Purchase Order eliminado con éxito',
        },
        destroyAll: {
          success: 'Purchase Order(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Purchase Order',
        },
        fields: {
          id: 'Id',
          'purchaseOrderNumberRange': 'Purchase Order Number',
          'purchaseOrderNumber': 'Purchase Order Number',
          'vendor': 'Vendor',
          'submittedDateRange': 'Submitted Date',
          'submittedDate': 'Submitted Date',
          'sumEntriesCostRange': 'Sum of Entry Costs',
          'sumEntriesCost': 'Sum of Entry Costs',
          'entries': 'Entries',
          'invoices': 'Invoices',
          'purchaseOrderLookup': 'PurchaseOrderLookup',
          'totalGSTRange': 'Total GST',
          'totalGST': 'Total GST',
          'freightAmountRange': 'Freight Amount',
          'freightAmount': 'Freight Amount',
          'discountRange': 'Discount',
          'discount': 'Discount',
          'writeOffAmountRange': 'R/Off Amount',
          'writeOffAmount': 'R/Off Amount',
          'netAmountRange': 'Net Amount',
          'netAmount': 'Net Amount',
          'notes': 'Notes',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {
          'purchaseOrderNumber': 'Autogenerated by system',
          'sumEntriesCost': 'Autogenerated based on cost of entries',
          'purchaseOrderLookup': 'Autogenerated by system',
        },
        new: {
          title: 'Nuevo Purchase Order',
        },
        view: {
          title: 'Ver Purchase Order',
        },
        importer: {
          title: 'Importar PurchaseOrders',
          fileName: 'purchaseOrder_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    purchaseOrderEntry: {
        name: 'purchaseOrderEntry',
        label: 'PurchaseOrderEntries',
        menu: 'PurchaseOrderEntries',
        exporterFileName: 'exportacion_purchaseOrderEntry',
        list: {
          menu: 'PurchaseOrderEntries',
          title: 'PurchaseOrderEntries',
        },
        create: {
          success: 'Purchase Order Entry guardado con éxito',
        },
        update: {
          success: 'Purchase Order Entry guardado con éxito',
        },
        destroy: {
          success: 'Purchase Order Entry eliminado con éxito',
        },
        destroyAll: {
          success: 'Purchase Order Entry(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Purchase Order Entry',
        },
        fields: {
          id: 'Id',
          'purchaseOrder': 'Purchase Order',
          'medicine': 'Medicine',
          'quantityRange': 'Quantity',
          'quantity': 'Quantity',
          'unit': 'Unit',
          'unitCostRange': 'Unit Cost',
          'unitCost': 'Unit Cost',
          'totalCostRange': 'Total Cost',
          'totalCost': 'Total Cost',
          'stateGSTRange': 'StateGST',
          'stateGST': 'StateGST',
          'centralGSTRange': 'Central GST',
          'centralGST': 'Central GST',
          'substitutionAllowed': 'Substitution Allowed',
          'purchaseOrderEntryLookup': 'PurchaseOrder Entry Lookup',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {
          'unit': {
            'Tablets': 'Tablets',
            'Strips': 'Strips',
            'Bottle': 'Bottle',
            'Tube': 'Tube',
            'Drop': 'Drop',
          },
        },
        placeholders: {

        },
        hints: {
          'purchaseOrderEntryLookup': 'Auto-filled in',
        },
        new: {
          title: 'Nuevo Purchase Order Entry',
        },
        view: {
          title: 'Ver Purchase Order Entry',
        },
        importer: {
          title: 'Importar PurchaseOrderEntries',
          fileName: 'purchaseOrderEntry_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    medicineBatch: {
        name: 'medicineBatch',
        label: 'Medicine Batches',
        menu: 'Medicine Batches',
        exporterFileName: 'exportacion_medicineBatch',
        list: {
          menu: 'Medicine Batches',
          title: 'Medicine Batches',
        },
        create: {
          success: 'Medicine Batch guardado con éxito',
        },
        update: {
          success: 'Medicine Batch guardado con éxito',
        },
        destroy: {
          success: 'Medicine Batch eliminado con éxito',
        },
        destroyAll: {
          success: 'Medicine Batch(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Medicine Batch',
        },
        fields: {
          id: 'Id',
          'invoice': 'Invoice',
          'medicine': 'Medicine',
          'quantityRange': 'Quantity',
          'quantity': 'Quantity',
          'unit': 'Unit',
          'qtyInStrips': 'Quantity In Strips',
          'batchNumber': 'Batch Number',
          'expiryDateRange': 'Expiry Date',
          'expiryDate': 'Expiry Date',
          'unitPriceRange': 'UnitPrice',
          'unitPrice': 'UnitPrice',
          'totalPriceRange': 'TotalPrice',
          'totalPrice': 'TotalPrice',
          'stateGSTRange': 'StateGST',
          'stateGST': 'StateGST',
          'centralGSTRange': 'CentralGST',
          'centralGST': 'CentralGST',
          'msrpRange': 'MSRP',
          'msrp': 'MSRP',
          'description': 'Description',
          'medicineBatchLookup': 'Medicine Batch Lookup',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {
          'unit': {
            'Tablets': 'Tablets',
            'Strips': 'Strips',
            'Bottle': 'Bottle',
            'Tube': 'Tube',
            'Drop': 'Drop',
          },
        },
        placeholders: {
          'unit': 'Tablet',
        },
        hints: {
          'qtyInStrips': 'Qty in strips or tablets. Strips * Tablets/Strip = Qty',
          'medicineBatchLookup': 'Autogenerated by system',
        },
        new: {
          title: 'Nuevo Medicine Batch',
        },
        view: {
          title: 'Ver Medicine Batch',
        },
        importer: {
          title: 'Importar Medicine Batches',
          fileName: 'medicineBatch_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    purchaseInvoice: {
        name: 'purchaseInvoice',
        label: 'PurchaseInvoices',
        menu: 'PurchaseInvoices',
        exporterFileName: 'exportacion_purchaseInvoice',
        list: {
          menu: 'PurchaseInvoices',
          title: 'PurchaseInvoices',
        },
        create: {
          success: 'Purchase Invoice guardado con éxito',
        },
        update: {
          success: 'Purchase Invoice guardado con éxito',
        },
        destroy: {
          success: 'Purchase Invoice eliminado con éxito',
        },
        destroyAll: {
          success: 'Purchase Invoice(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Purchase Invoice',
        },
        fields: {
          id: 'Id',
          'purchaseOrder': 'Purchase Order',
          'invoiceNumber': 'Invoice Number',
          'referenceNumber': 'ReferenceNumber',
          'batches': 'Batches',
          'grossAmountRange': 'Gross Amount',
          'grossAmount': 'Gross Amount',
          'stateGSTRange': 'State GST',
          'stateGST': 'State GST',
          'centralGSTRange': 'Central GST',
          'centralGST': 'Central GST',
          'grandTotalRange': 'Grand Total',
          'grandTotal': 'Grand Total',
          'invoiceDateRange': 'InvoiceDate',
          'invoiceDate': 'InvoiceDate',
          'invoicePaidDateRange': 'Invoice Paid Date',
          'invoicePaidDate': 'Invoice Paid Date',
          'paymentDetails': 'Payment Details',
          'inventoryAddDateRange': 'Inventory Added Date',
          'inventoryAddDate': 'Inventory Added Date',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Purchase Invoice',
        },
        view: {
          title: 'Ver Purchase Invoice',
        },
        importer: {
          title: 'Importar PurchaseInvoices',
          fileName: 'purchaseInvoice_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    transfer: {
        name: 'transfer',
        label: 'Transfers',
        menu: 'Transfers',
        exporterFileName: 'exportacion_transfer',
        list: {
          menu: 'Transfers',
          title: 'Transfers',
        },
        create: {
          success: 'Transfer guardado con éxito',
        },
        update: {
          success: 'Transfer guardado con éxito',
        },
        destroy: {
          success: 'Transfer eliminado con éxito',
        },
        destroyAll: {
          success: 'Transfer(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Transfer',
        },
        fields: {
          id: 'Id',
          'fromCenter': 'FromCenter',
          'toCenter': 'ToCenter',
          'medicineBatch': 'MedicineBatch',
          'transferQuantityRange': 'Transfer Quantity',
          'transferQuantity': 'Transfer Quantity',
          'transferDateRange': 'Transfer Date',
          'transferDate': 'Transfer Date',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {

        },
        new: {
          title: 'Nuevo Transfer',
        },
        view: {
          title: 'Ver Transfer',
        },
        importer: {
          title: 'Importar Transfers',
          fileName: 'transfer_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    prescriptionFill: {
        name: 'prescriptionFill',
        label: 'Prescription Fills',
        menu: 'Prescription Fills',
        exporterFileName: 'exportacion_prescriptionFill',
        list: {
          menu: 'Prescription Fills',
          title: 'Prescription Fills',
        },
        create: {
          success: 'Prescription Fill guardado con éxito',
        },
        update: {
          success: 'Prescription Fill guardado con éxito',
        },
        destroy: {
          success: 'Prescription Fill eliminado con éxito',
        },
        destroyAll: {
          success: 'Prescription Fill(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Prescription Fill',
        },
        fields: {
          id: 'Id',
          'patientVisit': 'PatientVisit',
          'siteInventory': 'SiteInventory',
          'quantityRange': 'Quantity',
          'quantity': 'Quantity',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {
          'siteInventory': 'Local medicine inventory batch at the center',
        },
        new: {
          title: 'Nuevo Prescription Fill',
        },
        view: {
          title: 'Ver Prescription Fill',
        },
        importer: {
          title: 'Importar Prescription Fills',
          fileName: 'prescriptionFill_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },

    staff: {
        name: 'staff',
        label: 'Staff',
        menu: 'Staff',
        exporterFileName: 'exportacion_staff',
        list: {
          menu: 'Staff',
          title: 'Staff',
        },
        create: {
          success: 'Staff guardado con éxito',
        },
        update: {
          success: 'Staff guardado con éxito',
        },
        destroy: {
          success: 'Staff eliminado con éxito',
        },
        destroyAll: {
          success: 'Staff(s) eliminado con éxito',
        },
        edit: {
          title: 'Editar Staff',
        },
        fields: {
          id: 'Id',
          'name': 'Name',
          'mobileNumber': 'MobileNumber',
          'user': 'User',
          'center': 'Center',
          createdAt: 'Creado el',
          updatedAt: 'Actualizado el',
          createdAtRange: 'Creado el',
        },
        enumerators: {

        },
        placeholders: {

        },
        hints: {
          'name': 'autogenerated by system',
        },
        new: {
          title: 'Nuevo Staff',
        },
        view: {
          title: 'Ver Staff',
        },
        importer: {
          title: 'Importar Staff',
          fileName: 'staff_import_template',
          hint:
            'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio.',
        },
      },
  },
  auth: {
    tenants: 'Espacios de trabajo',
    profile: {
      title: 'Perfil',
      success: 'Perfil actualizado con éxito',
    },
    createAnAccount: 'Crea una cuenta',
    rememberMe: 'Recuérdame',
    forgotPassword: 'Se te olvidó tu contraseña',
    signin: 'Iniciar Sesión',
    signup: 'Registrarse',
    signout: 'Desconectar',
    alreadyHaveAnAccount:
      '¿Ya tienes una cuenta? Registrarse.',
    social: {
      errors: {
        'auth-invalid-provider':
          'This email is already registered to another provider.',
        'auth-no-email': `The email associated with this account is private or inexistent.`,
      },
    },
    signinWithAnotherAccount:
      'Inicia sesión con otra cuenta',
    passwordChange: {
      title: 'Cambia la contraseña',
      success: 'Contraseña cambiada correctamente',
      mustMatch: 'Las contraseñas deben coincidir',
    },
    emailUnverified: {
      message:
        'Confirme su correo electrónico en <strong>{0}</strong> para continuar.',
      submit: 'Reenviar verificación de correo electrónico',
    },
    emptyPermissions: {
      message:
        'Aún no tienes permisos. Espera a que el administrador te otorgue privilegios.',
    },
    passwordResetEmail: {
      message:
        'Enviar contraseña restablecer correo electrónico',
      error: 'Correo electrónico no reconocido',
    },
    passwordReset: {
      message: 'Restablecer la contraseña',
    },
    emailAddressVerificationEmail: {
      error: 'Correo electrónico no reconocido',
    },
    verificationEmailSuccess:
      'Correo electrónico de verificación enviado con éxito',
    passwordResetEmailSuccess:
      'Correo electrónico de restablecimiento de contraseña enviado correctamente',
    passwordResetSuccess:
      'Contraseña cambiada correctamente',
    verifyEmail: {
      success: 'Correo electrónico verificado con éxito.',
      message:
        'Solo un momento, su correo electrónico está siendo verificado ...',
    },
  },
  tenant: {
    name: 'inquilino',
    label: 'Espacios de trabajo',
    menu: 'Espacios de trabajo',
    list: {
      menu: 'Espacios de trabajo',
      title: 'Espacios de trabajo',
    },
    create: {
      button: 'Crear espacio de trabajo',
      success: 'Espacio de trabajo guardado correctamente',
    },
    update: {
      success: 'Espacio de trabajo guardado correctamente',
    },
    destroy: {
      success: 'Espacio de trabajo eliminado correctamente',
    },
    destroyAll: {
      success:
        'Espacio(s) de trabajo eliminado(s) correctamente',
    },
    edit: {
      title: 'Editar espacio de trabajo',
    },
    fields: {
      id: 'Id',
      name: 'Nombre',
      url: 'URL',
      tenantName: 'Nombre del espacio de trabajo',
      tenantId: 'Espacio de trabajo',
      tenantUrl: 'URL del espacio de trabajo',
      plan: 'Plan',
    },
    enumerators: {},
    new: {
      title: 'Nuevo espacio de trabajo',
    },
    invitation: {
      view: 'Ver invitaciones',
      invited: 'Invitado',
      accept: 'Aceptar la invitacion',
      decline: 'Rechazar invitación',
      declined: 'Invitación rechazada con éxito',
      acceptWrongEmail:
        'Aceptar invitación con este correo electrónico',
    },
    select: 'Seleccionar espacio de trabajo',
    validation: {
      url:
        'La URL de su espacio de trabajo solo puede contener letras minúsculas, números y guiones (y debe comenzar con una letra o número).',
    },
  },
  roles: {
    admin: {
      label: 'Administración',
      description: 'Acceso total a todos los recursos.',
    },
    custom: {
      label: 'Rol personalizado',
      description: 'Acceso personalizado a recursos',
    },
  },
  user: {
    invite: 'Invitación',
    title: 'Usuarios',
    menu: 'Usuarios',
    fields: {
      id: 'Id',
      avatars: 'Avatar',
      email: 'Email',
      emails: 'Email(s)',
      fullName: 'Nombre completo',
      firstName: 'Nombre',
      lastName: 'Apellido',
      status: 'Estado',
      disabled: 'Discapacitado',
      phoneNumber: 'Número de teléfono',
      role: 'Rol',
      createdAt: 'Creado el',
      updatedAt: 'Actualizado el',
      roleUser: 'Rol/Usuario',
      roles: 'Roles',
      createdAtRange: 'Creado el',
      password: 'Contraseña',
      rememberMe: 'Recuérdame',
      oldPassword: 'Contraseña anterior',
      newPassword: 'Nueva contraseña',
      newPasswordConfirmation:
        'Nueva confirmación de contraseña',
    },
    enabled: 'Habilitado',
    disabled: 'Discapacitado',
    validations: {
      // eslint-disable-next-line
      email: 'El correo electrónico ${value} no es válido',
    },
    disable: 'Inhabilitar',
    enable: 'Habilitar',
    doEnableSuccess: 'Usuario habilitado con éxito',
    doDisableSuccess: 'Usuario deshabilitado con éxito',
    doDisableAllSuccess:
      'Usuario(s) deshabilitado con éxito',
    doEnableAllSuccess:
      'Usuario(s) habilitados correctamente',
    doAddSuccess: 'Usuario(s) guardado correctamente',
    doUpdateSuccess: 'Usuario guardado con éxito',
    status: {
      active: 'Activo',
      invited: 'Invitado',
      'empty-permissions': 'Esperando permisos',
    },
    exporterFileName: 'usuarios_exportacion',
    doDestroySuccess: 'Usuario eliminado con éxito',
    doDestroyAllSelectedSuccess:
      'Usuario(s) eliminado correctamente',
    edit: {
      title: 'Editar Usuario',
    },
    new: {
      title: 'Invitar Usuario(s)',
      titleModal: 'Nuevo Usuario',
      emailsHint:
        'Separe varias direcciones de correo electrónico utilizando el carácter de coma.',
    },
    view: {
      title: 'Ver Usuario',
      activity: 'Actividad',
    },
    importer: {
      title: 'Importar Usuarios',
      fileName: 'users_import_template',
      hint:
        'Las columnas Archivos/Imágenes deben ser las URL de los archivos separados por espacio. Las relaciones deben ser la ID de los registros referenciados separados por espacio. Los roles deben ser los identificadores de roles separados por espacio.',
    },
    errors: {
      userAlreadyExists:
        'El usuario con este correo electrónico ya existe',
      userNotFound: 'Usuario no encontrado',
      disablingHimself: 'No puedes inhabilitarte',
      revokingOwnPermission:
        'No puede revocar su propio permiso de administrador',
    },
  },
  plan: {
    menu: 'Planes',
    title: 'Planes',
    free: {
      label: 'Gratis',
      price: '$0',
    },
    growth: {
      label: 'Crecimiento',
      price: '$10',
    },
    enterprise: {
      label: 'Empresa',
      price: '$50',
    },
    pricingPeriod: '/mes',
    current: 'Plan Actual',
    subscribe: 'Suscribir',
    manage: 'Administrar Suscripción',
    cancelAtPeriodEnd:
      'Este plan se cancelará al final del período.',
    somethingWrong:
      'Hay algo mal con su suscripción. Vaya a administrar la suscripción para obtener más detalles.',
    notPlanUser:
      'No eres el administrador de esta suscripción.',
    demoHintHtml:
      'Sugerencia: Use esas <a href="https://stripe.com/docs/testing#cards" target="_blank" rel="noopener noreferrer">tarjetas de prueba</a> para la demostración.',
  },
  auditLog: {
    menu: 'Registros de auditoría',
    title: 'Registros de auditoría',
    exporterFileName: 'audit_log_export',
    entityNamesHint:
      'Separe varias entidades con el carácter de coma.',
    fields: {
      id: 'Id',
      timestampRange: 'Período',
      entityName: 'Entidad',
      entityNames: 'Entidades',
      entityId: 'ID de entidad',
      action: 'Acción',
      values: 'Valores',
      timestamp: 'Fecha',
      createdByEmail: 'Email del usuario',
    },
  },
  settings: {
    title: 'Configuraciones',
    menu: 'Configuraciones',
    save: {
      success:
        'Configuración guardada con éxito. La página se volverá a cargar en {0} segundos para que los cambios surtan efecto.',
    },
    fields: {
      primary: 'Color primario',
      secondary: 'Color secundario',
      logos: 'Logo',
      backgroundImages: 'Imágenes de fondo',
      shade: 'Sombra',
    },
  },
  dashboard: {
    menu: 'Tablero',
    message:
      'Esta página utiliza datos falsos solo con fines de demostración. Puede editarlo en frontend/view/dashboard/DashboardPage.ts.',
    charts: {
      day: 'Día',
      red: 'Rojo',
      green: 'Verde',
      yellow: 'Amarillo',
      grey: 'Gris',
      blue: 'Azul',
      orange: 'Naranja',
      months: {
        '1': 'Enero',
        '2': 'Febrero',
        '3': 'Marzo',
        '4': 'Abril',
        '5': 'Mayo',
        '6': 'Junio',
        '7': 'Julio',
      },
      eating: 'Comiendo',
      drinking: 'Bebiendo',
      sleeping: 'Dormiendo',
      designing: 'Diseñando',
      coding: 'Codificando',
      cycling: 'Pedalando',
      running: 'Corriendo',
      customer: 'Cliente',
    },
  },
  errors: {
    '403': 'Lo sentimos, no tienes acceso a esta página',
    '404': 'Lo sentimos, la página que visitaste no existe',
    '500': 'Lo sentimos, el servidor informa un error',
    '429':
      'Demasiadas solicitudes. Por favor, inténtelo de nuevo más tarde.',
    backToHome: 'Volver a Inicio',
    forbidden: {
      message: 'Prohibido',
    },
    validation: {
      message: 'Ocurrió un error',
    },
    defaultErrorMessage: 'Ops, ocurrió un error',
  },
  
  preview: {
    error:
      'Lo sentimos, esta operación no está permitida en el modo de vista previa.',
  },

  /* eslint-disable */
  validation: {
    mixed: {
      default: '${path} no es válido',
      required: '${path} es obligatorio',
      oneOf:
        '${path} debe ser uno de los siguientes valores: ${values}',
      notOneOf:
        '${path} no debe ser uno de los siguientes valores: ${values}',
      notType: ({ path, type, value, originalValue }) => {
        return `${path} debe ser un ${type}`;
      },
    },
    string: {
      length:
        '${path} debe tener exactamente ${length} caracteres',
      min: '${path} debe tener al menos ${min} caracteres',
      max:
        '${path} debe tener como máximo ${max} caracteres',
      matches:
        '${path} debe coincidir con lo siguiente: "${regex}"',
      email:
        '${path} debe ser un correo electrónico válido',
      url: '${path} debe ser una URL válida',
      trim: '${path} debe ser una cadena recortada',
      lowercase:
        '${path} debe ser una cadena en minúsculas',
      uppercase: '${path} debe ser una cadena en mayúscula',
      selected: '${path} debe estar seleccionado',
    },
    number: {
      min: '${path} debe ser mayor o igual que ${min}',
      max: '${path} debe ser menor o igual que ${max}',
      lessThan: '${path} debe ser menor que ${less}',
      moreThan: '${path} debe ser mayor que ${more}',
      notEqual: '${path} no debe ser igual a ${notEqual}',
      positive: '${path} debe ser un número positivo',
      negative: '${path} debe ser un número negativo',
      integer: '${path} debe ser un número entero',
    },
    date: {
      min: 'El campo ${path} debe ser posterior a ${min}',
      max: 'El campo ${path} debe ser anterior a ${max}',
    },
    boolean: {},
    object: {
      noUnknown:
        'El campo ${path} no puede tener claves no especificadas en la forma del objeto',
    },
    array: {
      min: ({ min, path }) =>
        min === 1
          ? `${path} es obligatorio`
          : `'El campo ${path} debe tener al menos ${min} elementos`,
      max:
        'El campo ${path} debe tener elementos menores o iguales a ${max}',
    },
  },
  fileUploader: {
    upload: 'Subir',
    image: 'Debes subir una imagen',
    size:
      'El archivo es muy grande. El tamaño máximo permitido es {0}',
    formats: 'Formato inválido. Debe ser uno de: {0}.',
  },
  importer: {
    line: 'Línea',
    status: 'Estado',
    pending: 'Pendiente',
    imported: 'Importado',
    error: 'Error',
    total: '{0} importado, {1} pendiente y {2} con error',
    importedMessage: 'Procesado {0} de {1}.',
    noNavigateAwayMessage:
      'No navegue fuera de esta página o la importación se detendrá.',
    completed: {
      success:
        'Importación completada. Todas las filas se importaron correctamente.',
      someErrors:
        'Procesamiento completado, pero algunas filas no se pudieron importar.',
      allErrors:
        'Importación fallida. No hay filas válidas.',
    },
    form: {
      downloadTemplate: 'Descargar la plantilla',
      hint:
        'Haga clic o arrastre el archivo a esta área para continuar.',
    },
    list: {
      discardConfirm:
        '¿Estás seguro? Los datos no importados se perderán.',
    },
    errors: {
      invalidFileEmpty: 'El archivo esta vacio',
      invalidFileExcel:
        'Solo se permiten archivos de Excel(.xlsx)',
      invalidFileUpload:
        'Archivo inválido. Asegúrese de estar utilizando la última versión de la plantilla.',
      importHashRequired: 'Se requiere hash de importación',
      importHashExistent:
        'Los datos ya han sido importados',
    },
  },

  autocomplete: {
    loading: 'Cargando...',
    noOptions: 'Datos no encontrados',
  },
  imagesViewer: {
    noImage: 'Sin imágen',
  },
  table: {
    noData: 'No se encontraron registros',
    loading: 'Cargando...',
  },
  pagination: {
    labelDisplayedRows: '{0}-{1} de {2}',
    labelRowsPerPage: 'Por página:',
  },
};

export default es;
